import { z, defineCollection } from 'astro:content';

const baseMetadata = {
  keywords: z.array(z.string()).default([]),
  language: z.enum(['ko', 'en', 'both']).default('en'),
};

const blogCollection = defineCollection({
  type: 'content',
  schema: z.object({
    title: z.string(),
    title_en: z.string().optional(),
    excerpt: z.string(),
    excerpt_en: z.string().optional(),
    date: z.coerce.date(),
    updatedDate: z.coerce.date().optional(),
    category: z.string(),
    tags: z.array(z.string()),
    image: z.string().optional(),
    author: z.string().default('Yonghee Kim'),
    enableShare: z.boolean().default(true),
    ...baseMetadata,
    readingTime: z.number().optional(),
    wordCount: z.number().optional(),
    series: z.string().optional(),
    seriesOrder: z.number().optional(),
    relatedPosts: z.array(z.string()).default([]),
    views: z.number().default(0),
  }),
});

const publicationCollection = defineCollection({
  type: 'content',
  schema: z.object({
    title: z.string(),
    authors: z.array(z.string()),
    journal: z.string(),
    year: z.number(),
    type: z.string(),
    status: z.string(),
    category: z.string(),
    abstract: z.string(),
    volume: z.number().optional(),
    issue: z.union([z.string(), z.number()]).optional(),
    pages: z.string().optional(),
    doi: z.string().optional(),
    pdf: z.string().optional(),
    citations: z.number().default(0),
    impact_factor: z.number().optional(),
    quartile: z.string().optional(),
    publisher: z.string().optional(),
    ...baseMetadata,
    research_area: z.array(z.string()).default([]),
    methodology: z.array(z.string()).default([]),
    data_period: z.object({
      start: z.string(),
      end: z.string(),
    }).optional(),
    sample_size: z.number().optional(),
    statistical_methods: z.array(z.string()).default([]),
    software_used: z.array(z.string()).default([]),
    funding: z.object({
      agency: z.string(),
      amount: z.number().optional(),
      grant_number: z.string().optional(),
    }).optional(),
    related_projects: z.array(z.string()).default([]),
  }),
});

const projectCollection = defineCollection({
  type: 'content',
  schema: z.object({
    title: z.string(),
    title_en: z.string().optional(),
    title_ko: z.string().optional(),
    subtitle: z.string().optional(),
    subtitle_en: z.string().optional(),
    subtitle_ko: z.string().optional(),
    date: z.coerce.date(),
    updatedDate: z.coerce.date().optional(),
    category: z.string(),
    tags: z.array(z.string()),
    ...baseMetadata,
    conference: z.string().optional(),
    conference_en: z.string().optional(),
    conference_ko: z.string().optional(),
    venue: z.string().optional(),
    description: z.string(),
    description_en: z.string().optional(),
    summary: z.string(),
    summary_en: z.string().optional(),
    key_findings: z.array(z.string()),
    key_findings_ko: z.array(z.string()).optional(),
    policy_proposals: z.array(z.string()).optional(),
    policy_concerns: z.array(z.string()).optional(),
    methodology: z.array(z.string()).default([]),
    data_period: z.object({
      start: z.string(),
      end: z.string(),
    }).optional(),
    sample_size: z.number().optional(),
    data_sources: z.array(z.object({
      name: z.string(),
      url: z.string().optional(),
      type: z.enum(['primary', 'secondary']).default('primary'),
    })).default([]),
    related_publications: z.array(z.string()).default([]),
    related_projects: z.array(z.string()).default([]),
    featured: z.boolean().default(false),
    impact_metrics: z.object({
      views: z.number().default(0),
      downloads: z.number().default(0),
      citations: z.number().default(0),
    }).optional(),
    image: z.string().optional(),
    images: z.array(z.string()).optional(),
    video_url: z.string().optional(),
    funding: z.object({
      agency: z.string(),
      amount: z.number().optional(),
      grant_number: z.string().optional(),
    }).optional(),
  }),
});

export const collections = {
  'blog': blogCollection,
  'publications': publicationCollection,
  'projects': projectCollection,
};
